name = "nuclear"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-15"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "95fad5ff767b479f836be410f407448f"
routes = [
 
  { pattern = "nuclear.benxxinquins.workers.dev", custom_domain = true },
  { pattern = "cache.netflix.com.nuclear.benxxinquins.workers.dev", custom_domain = true },
  { pattern = "api24-normal.tiktokv.com.nuclear.benxxinquins.workers.dev", custom_domain = true },
  { pattern = "df.game.naver.com.nuclear.benxxinquins.workers.dev", custom_domain = true },

  ]

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
MAIN_PAGE_URL = "https://www.zeinthhub.xinquins.dpdns.org"
PROXY_KV_URL = "https://server.nuclear.xx.kg/best-latency.json"
